version: '3.7'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'on-failure:10'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - '8070'
      - '80'
    ports:
      - '8070:8070'
      - '80:80'
    environment:
      - MONGO_CONN_STRING=''
      - HOST=172.17.0.1
      - DOMAIN=localhost
      - SCHEME=http
    network_mode: bridge
  frontend:
    build:
      context: ./resources
      dockerfile: Dockerfile
    restart: 'on-failure:10'
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      - HOST_ENV=DEV
    network_mode: bridge